---
- hosts: all

  tasks:

  - name: Create `/vagrant/project`
    file:
      path: "{{ project_dir }}"
      owner: "{{ ansible_env.USER }}"
      group: "{{ ansible_env.USER }}"
      state: directory
      recurse: true

- include: playbooks/middleware.yml
- include: playbooks/openstreetmap-carto.yml
