---
- hosts: all

  tasks:

  - name: Create `/vagrant/files`
    file:
      path: "{{ files_dir }}/project"
      owner: "{{ ansible_env.USER }}"
      group: "{{ ansible_env.USER }}"
      state: directory
      recurse: true

- include: playbooks/middleware.yml
- include: playbooks/openstreetmap-carto.yml
