---
- hosts: all

  vars:
    project_dir: "{{ ansible_env.HOME }}/tilemill/project"
    db:
      name: gis
      encoding: UTF-8

  tasks:

  - name: Create a database `{{ db.name }}`
    become: yes
    become_user: postgres
    postgresql_db:
      name: "{{ db.name }}"
      encoding: "{{ db.encoding }}"
      owner: "{{ ansible_env.USER }}"

  - name: Run SQL `CREATE EXTENSION IF NOT EXISTS hstore;`
    become: yes
    become_user: postgres
    shell: "psql -c \"CREATE EXTENSION IF NOT EXISTS hstore;\" -d {{ db.name }}"

  - name: Run SQL `CREATE EXTENSION IF NOT EXISTS postgis;`
    become: yes
    become_user: postgres
    shell: "psql -c \"CREATE EXTENSION IF NOT EXISTS postgis;\" -d {{ db.name }}"

  # OpenStreetMap Carto
  - name: Clone the openstreetmap-carto
    git:
      repo: https://github.com/gravitystorm/openstreetmap-carto.git
      dest: "{{ project_dir }}/openstreetmap-carto"
      update: no

  - name: Import the default data
    shell: "osm2pgsql --slim -d gis -C 3600 --cache {{ memory * 0.5 }} --hstore -S {{ project_dir }}/openstreetmap-carto/openstreetmap-carto.style {{ osm2pgsql.data }}"

  - name: Run `./scripts/get-shapefiles.py`
    become: yes
    shell: ./scripts/get-shapefiles.py
    args:
      chdir: "{{ project_dir }}/openstreetmap-carto"

  - name: Run `carto project.mml > style.xml`
    become: yes
    shell: carto project.mml > style.xml
    args:
      chdir: "{{ project_dir }}/openstreetmap-carto"

  - name: "Create symlink into `{{ ansible_env.HOME }}/tilemill/project/openstreetmap-carto`"
    become: yes
    file:
      src: "{{ project_dir }}/openstreetmap-carto"
      path: "{{ ansible_env.HOME }}/tilemill/project/openstreetmap-carto"
      state: link
