---
- hosts: all

  vars:
    osm_carto:
      version: 3.1.0
    project_dir: "{{ files_dir }}/project/carto"

  tasks:

  # OpenStreetMap Carto
  - name: Clone the openstreetmap-carto
    git:
      repo: https://github.com/gravitystorm/openstreetmap-carto.git
      dest: /usr/local/src/tilemill

  - name: Import the default data
    shell: "osm2pgsql --slim -d gis -C 3600 --cache {{ memory * 0.5 }} --hstore -S {{ project_dir }}/openstreetmap-carto-{{ osm_carto.version }}/openstreetmap-carto.style {{ osm2pgsql.data }}"

  - name: Generate a Mapnik Stylesheet
    become: yes
    shell: ./scripts/get-shapefiles.py && carto project.mml > style.xml
    args:
      chdir: "{{ project_dir }}"
    notify:
      - restart-renderd

  - name: Setup renderd
    become: yes
    replace:
      dest: /usr/local/etc/renderd.conf
      regexp: ^XML=.*
      replace: "XML={{ project_dir }}/style.xml"
    notify:
      - restart-renderd

  - name: Start `kosmtic` as a server
    shell: "pm2 -f start kosmtik -- serve {{ project_dir }}/project.mml --host=0.0.0.0 --localconfig={{ ansible_env.HOME }}/.kosmtik.json"
    args:
      chdir: "{{ ansible_env.HOME }}"

  handlers:
    - name: restart-apache
      become: yes
      action: service name=apache2 state=restarted
    - name: restart-renderd
      become: yes
      action: service name=renderd state=restarted
