---
- hosts: all

  vars:
    osm_carto:
      version: 3.1.0
    project_dir: "{{ files_dir }}/project"
    db_name: osm_carto

  tasks:

  - name: Create a database `{{ db.name }}`
    become: yes
    become_user: postgres
    postgresql_db:
      name: "{{ osm_carto }}"
      encoding: "{{ db.encoding }}"
      owner: "{{ ansible_env.USER }}"

  - name: Run SQL `CREATE EXTENSION IF NOT EXISTS hstore;`
    become: yes
    become_user: postgres
    shell: "psql -c \"CREATE EXTENSION IF NOT EXISTS hstore;\" -d {{ osm_carto }}"

  - name: Run SQL `CREATE EXTENSION IF NOT EXISTS postgis;`
    become: yes
    become_user: postgres
    shell: "psql -c \"CREATE EXTENSION IF NOT EXISTS postgis;\" -d {{ osm_carto }}"

  # OpenStreetMap Carto
  - name: Download & Unarchive openstreetmap-carto
    become: yes
    unarchive:
      src: "https://github.com/gravitystorm/openstreetmap-carto/archive/v{{ osm_carto.version }}.tar.gz"
      dest: "{{ project_dir }}"
      remote_src: true

  - name: Import the default data
    shell: "osm2pgsql --slim -d gis -C 3600 --cache {{ memory * 0.5 }} --hstore -S {{ project_dir }}/openstreetmap-carto-{{ osm_carto.version }}/openstreetmap-carto.style {{ osm2pgsql.data }}"

  - name: Generate a Mapnik Stylesheet
    become: yes
    shell: ./scripts/get-shapefiles.py && carto project.mml > style.xml
    args:
      chdir: "{{ project_dir }}/openstreetmap-carto-{{ osm_carto.version }}"
    notify:
      - restart-renderd

  - name: Setup renderd
    become: yes
    replace:
      dest: /usr/local/etc/renderd.conf
      regexp: ^XML=.*
      replace: "XML={{ project_dir }}/openstreetmap-carto-{{ osm_carto.version }}/style.xml"
    notify:
      - restart-renderd

  - name: Start `kosmtic` as a server
    shell: "pm2 start kosmtik -- serve {{ project_dir }}/openstreetmap-carto-{{ osm_carto.version }}/project.mml --host=0.0.0.0 --localconfig={{ ansible_env.HOME }}/.kosmtik.json"
    args:
      chdir: "{{ ansible_env.HOME }}"
